### PR TITLE
fix segfault in rmw_connext_dynamic due to static initialize race

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/rmw_connext#30

### CODE REVIEW

**Comment by wjwwood** [comment]
I'm still testing this locally, the farm will not easily tell us because another segfault comes up later in the same test. I'll open a separate issue for that.

**Comment by dirk-thomas** [comment]
lgtm

**Comment by wjwwood** [comment]
@tfoote @esteve

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
@tfoote I'm going to merge, feel free to comment afterwards with feedback.

**Pull request merged**
