### PR TITLE
fix generated idl for static arrays of non-primitive types

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by jackieokay** [comment]
before I test, can you clarify if this is a fix for https://github.com/ros2/rosidl/issues/26? I am confused because https://github.com/ros2/rosidl/pull/27 presents a workaround but the title of this suggests it is a fix.

**Comment by dirk-thomas** [comment]
No, this patch fixed the generated .idl files.

ros2/rosidl#26 is about generating C code from the ROS .msg / .srv files.

**Comment by wjwwood** [comment]
+0 it's not clear at all why this is needed, but I assume it's ok.

**Comment by dirk-thomas** [comment]
Double colon in a type name are invalid in IDL.

**Comment by jackieokay** [comment]
+1 when I confirm https://github.com/ros2/rosidl_dds/pull/23 works

**Comment by tfoote** [comment]
+1

**Pull request merged**
