### PR TITLE
Expose .idl to DDS .idl conversion via rosidl translate CLI

### PR DESCRIPTION
**Pull request by hidmic**
Connected to https://github.com/ros2/rosidl/issues/565. Depends on https://github.com/ros2/rosidl/pull/575.

### CODE REVIEW

**Comment by ahcorde** [comment]
The CI job needs a release https://build.ros2.org/job/Rpr__rosidl_dds__ubuntu_focal_amd64/5/ for `rosidl_cli`, right ?

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by hidmic** [comment]
> The CI job needs a release https://build.ros2.org/job/Rpr__rosidl_dds__ubuntu_focal_amd64/5/ for rosidl_cli, right ?

Indeed!

Edit: https://github.com/ros/rosdistro/pull/28525 is up

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Review by ahcorde — APPROVED** [review]

**Comment by hidmic** [comment]
Running CI up to `rosidl_generator_dds_idl`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13859/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8714/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11568/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13947/)

**Comment by hidmic** [comment]
Re-running Windows CI after https://github.com/ros2/rosidl_dds/pull/55/commits/4bbea01e9d221b2b79cd55642f1fa32426b37795:

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13950/)

**Comment by hidmic** [comment]
Alright, CI's green, reviewer is OK with this patch. Going in!

**Pull request merged**
