### PR TITLE
Remove type support handle code

### PR DESCRIPTION
**Pull request by esteve**
This PR removes the type support handle headers and delegates the logic to rmw implementations.

Connects to ros2/ros2#18

### CODE REVIEW

**Comment by esteve** [comment]
Reviewable, but not mergeable.

**Comment by wjwwood** [comment]
The changes for this pull request don't appear to be on the `windows-disambiguate-linking` branch, is that pushed?

**Comment by esteve** [comment]
@wjwwood just pushed it.

**Comment by wjwwood** [comment]
Ok, I just pushed an update to it with the missing linux fixes from the windows branch.

**Comment by wjwwood** [comment]
By update I mean rebase, so you'll have to do a fetch and reset --hard.

**Comment by wjwwood** [comment]
Ok with these changes and the windows changes, I get this error on OS X:

```
Process package 'builtin_msgs' with context:
--------------------------------------------------------------------------------
 source_space => /Users/william/ros2/src/ros2/examples/builtin_msgs
  build_space => /Users/william/ros2/build/builtin_msgs
install_space => /Users/william/ros2/install
   make_flags => -j1
  build_tests => True
--------------------------------------------------------------------------------
+++ Building 'builtin_msgs'
==> '. /Users/william/ros2/build/builtin_msgs/ament_cmake__build.sh && /usr/bin/make cmake_check_build_system' in '/Users/william/ros2/build/builtin_msgs'
==> '. /Users/william/ros2/build/builtin_msgs/ament_cmake__build.sh && /usr/bin/make -j1' in '/Users/william/ros2/build/builtin_msgs'
[ 20%] Built target builtin_msgs__c
[ 40%] Built target builtin_msgs__cpp
Linking CXX shared library libbuiltin_msgs__typesupport_introspection_cpp.dylib
duplicate symbol __ZN36rosidl_typesupport_introspection_cpp36typesupport_introspection_identifierE in:
    CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/builtin_msgs/Duration_TypeSupport_Introspection.cpp.o
    CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/builtin_msgs/Time_TypeSupport_Introspection.cpp.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbuiltin_msgs__typesupport_introspection_cpp.dylib] Error 1
make[1]: *** [CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by esteve** [comment]
`typesupport_introspection_identifier` is defined both in:

`rmw_connext/rmw_connext_xtypes_dynamic_cpp/src/functions.cpp` and `rosidl_dds/rosidl_typesupport_introspection_cpp/src/identifier.cpp`

can any of the two be removed?

**Comment by wjwwood** [comment]
Not sure, I'll try to work it out.

**Comment by wjwwood** [comment]
I suppose the one in `rmw_connext/rmw_connext_xtypes_dynamic_cpp/src/functions.cpp` should go, I'll try that.

**Comment by wjwwood** [comment]
No, that still results in this:

```
Process package 'builtin_msgs' with context:
--------------------------------------------------------------------------------
 source_space => /Users/william/ros2/src/ros2/examples/builtin_msgs
  build_space => /Users/william/ros2/build/builtin_msgs
install_space => /Users/william/ros2/install
   make_flags => -j1
  build_tests => True
--------------------------------------------------------------------------------
+++ Building 'builtin_msgs'
==> '. /Users/william/ros2/build/builtin_msgs/ament_cmake__build.sh && /usr/bin/make cmake_check_build_system' in '/Users/william/ros2/build/builtin_msgs'
==> '. /Users/william/ros2/build/builtin_msgs/ament_cmake__build.sh && /usr/bin/make -j1' in '/Users/william/ros2/build/builtin_msgs'
[ 20%] Built target builtin_msgs__c
[ 40%] Built target builtin_msgs__cpp
[ 60%] Generating C++ introspection for ROS interfaces
Generating MESSAGE: /Users/william/ros2/build/builtin_msgs/rosidl_typesupport_introspection_cpp/builtin_msgs/Duration_TypeSupport_Introspection.cpp
Generating MESSAGE: /Users/william/ros2/build/builtin_msgs/rosidl_typesupport_introspection_cpp/builtin_msgs/Time_TypeSupport_Introspection.cpp
Scanning dependencies of target builtin_msgs__typesupport_introspection_cpp
[ 80%] Building CXX object CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/builtin_msgs/Duration_TypeSupport_Introspection.cpp.o
[100%] Building CXX object CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/builtin_msgs/Time_TypeSupport_Introspection.cpp.o
Linking CXX shared library libbuiltin_msgs__typesupport_introspection_cpp.dylib
duplicate symbol __ZN36rosidl_typesupport_introspection_cpp36typesupport_introspection_identifierE in:
    CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/builtin_msgs/Duration_TypeSupport_Introspection.cpp.o
    CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/builtin_msgs/Time_TypeSupport_Introspection.cpp.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbuiltin_msgs__typesupport_introspection_cpp.dylib] Error 1
make[1]: *** [CMakeFiles/builtin_msgs__typesupport_introspection_cpp.dir/all] Error 2
make: *** [all] Error 2
```

I think the issue is that a symbol is defined in both object files for `Time` and `Duration`. So that conflicting symbol, `rosidl_typesupport_introspection_cpp::typesupport_introspection_identifier`, needs to be hidden on those objects or defined in a third party.

**Comment by esteve** [comment]
@wjwwood are you ok with the approach in this PR? I'd prefer something more explicit than letting the linker decide what to do, but if this works on Windows too, it's a viable workaround IMO.

**Comment by wjwwood** [comment]
@esteve That's fine for now, I also still favor a set of tools for managing this in CMake and not depending on the linker, but I think we shouldn't focus on that for now. This whole toolchain may change if we find better solutions in the future for integrating with the middleware implementations.

**Comment by wjwwood** [comment]
I'm still testing on Windows.

**Comment by wjwwood** [comment]
I'll defer my testing on Windows until we get this merged, then I'll fix up the windows branches and merge them.

**Comment by dirk-thomas** [comment]
lgtm

**Pull request merged**
